### ISSUE TITLE
Support Java 11 based graalvm distributions

### ISSUE THREAD

**Issue by krzemin** [scalameta/sbt-native-image#7]
There are graalvm distributions based on Java 8 (`graalvm`) or Java 11 (`graalvm-java11`):

```
...
graalvm:19.0.0
graalvm:19.0.2
graalvm:19.1.0
graalvm:19.1.1
graalvm:19.2.0
graalvm:19.2.0-1
graalvm:19.2.1
graalvm:19.3.0
graalvm:19.3.1
graalvm:19.3.2
graalvm:20.0.0
graalvm:20.1.0
graalvm-java11:19.3.0
graalvm-java11:19.3.1
graalvm-java11:19.3.2
graalvm-java11:20.0.0
graalvm-java11:20.1.0
```

So far the plugin [hardcodes](https://github.com/scalameta/sbt-native-image/blob/master/plugin/src/main/scala/sbtnativeimage/NativeImagePlugin.scala#L101) `graalvm`, but it would be nice if we could select Java 11 based version too.

Btw, thanks for nice plugin 👍

**Comment by olafurpg** [comment]
Thank you for reporting! I debated whether I should introduce a `nativeImageJvm := "graalvm-java11"` setting key. It's currently possible to work around this with the settings
```scala
    nativeImageCommand := {
      val svmVersion = nativeImageVersion.value
      List(
        nativeImageCoursier.value.absolutePath,
        "launch",
        "--jvm",
        s"graalvm-java11:$svmVersion",
        s"org.graalvm.nativeimage:svm-driver:$svmVersion",
        "--"
      )
    }
```

I'm happy to merge a PR making this part configurable 👍

**Comment by krzemin** [comment]
Awesome, thank you 🎉
